export const ADD_ITEM="ADD_ITEM";
export const DELETE_ITEM="DELETE_ITEM";
export const DELETE_ITEM_FROM_STATE="DELETE_ITEM_FROM_STATE";
export const ADD_USER="ADD_USER";
export const CHECK_USER="CHECK_USER";